### PR TITLE
Scripting support

### PR DESCRIPTION
**Pull request by shawwn**
This PR introduces basic support for executing Lumen files directly:

- When the first argument to `lumen` ends with `.l`, pass it to `LOAD`
- Make `test.l` executable
- Define `WHEN-COMPILING`

Let me know any thoughts or changes you'd like me to make.

### CODE REVIEW

**Comment by sctb** [comment]
Can you think of a way to make this functionality apparent in the output of `lumen -h`?

**Comment by shawwn** [comment]
Here's an attempt.

**Comment by shawwn** [comment]
```
usage: lumen [<file> <arguments> | options <object files>]
 <file>		Program read from script file
 <arguments>	Passed to program in system.argv
 <object files>	Loaded before compiling <input>
options:
 -c <input>	Compile input file
 -o <output>	Output file
 -t <target>	Target language (default: lua)
 -e <expr>	Expression to evaluate
```

**Comment by sctb** [comment]
Multiple script files are support, yes? I'd make that clear and also that the suffix (*.l) matters.

**Comment by shawwn** [comment]
Only the first argument is loaded as a script. I considered supporting multiple script files (e.g. `lumen foo.l bar.l baz.l -- arg1 arg2`), but no other scripting system works that way, and I couldn't really think of a use case for it. Whereas I was hoping to write Lumen scripts such as `count-expressions.l runtime.l` to print out the size of the parse tree of `runtime.l`.

Rather than detect suffixes of *.l, could we execute the first argument as a script file if it doesn't begin with `-`? That would let people write shell scripts named `count-expressions` rather than forcing them to suffix it.

Alternatively, we could execute the first argument as a script if it doesn't end with `.js` or `.lua`. That would let people run `LUMEN_HOST=node lumen foo.js` and be dropped into a repl with `foo.js` loaded.

**Comment by sctb** [comment]
I think I would feel more comfortable adding a flag for this (`-f <script> <arguments>`, probably). How do you feel about that?

**Comment by shawwn** [comment]
Unfortunately that would make it impossible to write shell scripts, e.g. an executable file named `print-arguments`:

```
#!/usr/bin/env lumen
(define system (require 'system))
(print (str system.argv))
```

I think Lumen could be a nice shell scripting language like Python or Ruby, but users would want to be able to execute the script files directly.

It seems like the following code would support all existing `lumen` command line features while also providing script support:

```
(define script-file? (path)
  (not (or (= "-" (char path 0))
           (= ".js" (clip path (- (# path) 3)))
           (= ".lua" (clip path (- (# path) 4))))))
```

**Comment by shawwn** [comment]
If you want to stick with `-f`, I guess it would be straightforward to create a wrapper shell script, e.g.  a file named `lumen-script`:

```sh
exec lumen -f "$@"
```

Then users could write executable scripts like

```
#!/usr/bin/env lumen-script
(print (str (get (require 'system) 'argv)))
```

It'd be preferable to do without the `-f` and just use `lumen` directly, but let's go with whatever you think is best.

**Comment by sctb** [comment]
Let's go with this code as-is, but with your newer definition of `script-file?` that doesn't require the `*.l` extension.

**Comment by shawwn** [comment]
Ok, I pushed the newer definition of `script-file?`.

**Pull request merged**
