### PR TITLE
Define THROW and ERROR

### PR DESCRIPTION
**Pull request by shawwn**
This PR provides a way to rethrow an error.

### CODE REVIEW

**Comment by shawwn** [comment]
For example, this PR makes it possible to define a LET! macro that properly restores a global variable to its previous value, even if there was an error:

```
(define-macro let! (name value rest: body)
  (let-unique (prev)
    `(let (,prev ,name)
       (set ,name ,value)
       (let ((ok v) (guard (do ,@body)))
         (set ,name ,prev)
         (if ok v (throw v))))))
```
```
> (cat (indentation) "foo")
"foo"
> (let! indent-level 1 (cat (indentation) "foo"))
"  foo"
> (let! indent-level 1 (error 'bar) (cat (indentation) "foo"))
error: bar
> (cat (indentation) "foo")
"foo"
```

**Comment by sctb** [comment]
Does `error` need to be a special form?

**Comment by shawwn** [comment]
Nope. We can make `error` a global function on js. If you like this diff, let me know and I'll commit it:

```diff
diff --git a/compiler.l b/compiler.l
index bba2e12..399b49f 100644
--- a/compiler.l
+++ b/compiler.l
@@ -684,10 +684,6 @@
            (cat "error(" (compile x) ")"))
     (cat (indentation) e)))
 
-(define-special error (x) :stmt
-  (let x (if (= target 'js) `(new (Error ,x)) x)
-    (compile `(throw ,x))))
-
 (define-special %local (name value) :stmt
   (let (id (compile name)
         value1 (compile value)
diff --git a/runtime.l b/runtime.l
index 101e5d6..42f0fee 100644
--- a/runtime.l
+++ b/runtime.l
@@ -344,6 +344,10 @@
   (define-global print (x)
     ((get console 'log) x)))
 
+(target js:
+  (define-global error (x)
+    (throw (new (Error x)))))
+
 (define math (target js: Math lua: math))
 
 (define-global abs (get math 'abs))
```

**Comment by sctb** [comment]
I like it; let's go with that!

**Comment by shawwn** [comment]
Ok, ready to merge.

**Pull request merged**
