### PR TITLE
Fix `(- -1)` and `inf -inf nan -nan Inf -Inf NaN -NaN`

### PR DESCRIPTION
**Pull request by laarc**
Implemented as per https://github.com/sctb/lumen/pull/4#issuecomment-142685652.

I also added a space between each unary operator and its operand.  This solves cases like `(- -inf)` giving `--inf`. It now gives `- -inf`.

This works, but the compilation output is uglier now.  Can you think of a better fix?

### CODE REVIEW

**Comment by laarc** [comment]
On the other hand, the compiler now cleanly distinguishes between `-inf` and `- inf`, which seems like a good property:

```
  if not  equal63(-inf, - inf) then
    failed = failed + 1
    return("failed: expected " .. string(-inf) .. ", was " .. string(- inf))
  else
    passed = passed + 1
  end
  if not  equal63(inf, - -inf) then
    failed = failed + 1
    return("failed: expected " .. string(inf) .. ", was " .. string(- -inf))
  else
    passed = passed + 1
    return(passed)
  end
```

**Comment by laarc** [comment]
Just to clarify, this PR looks superficially similar to #4, but it works properly:

```
> (nan? ((get (require 'reader) 'read-string) "nan"))
true
```

It also incorporates a rather important fix that I was hoping to get merged into the mainline.

```
sctb-lumen$ bin/lumen
> (compile '(- -1))
"--1"
laarc-lumen$ bin/lumen 
> (compile '(- -1))
"- -1"
```
The fix is that `--1` is an error (because `--` means "line comment" on Lua) whereas `- -1` works correctly.

**Comment by laarc** [comment]
The fix to `(compile '(- -1))` was merged, but not the fix to `(nan? ((get (require 'reader) 'read-string) "nan"))`.

Would it be possible to merge the other two commits as well? (61ef9b5 and 385e8a8)

**Comment by sctb** [comment]
Yes, I know—I should have the time to look at the remaining commits today.

**Pull request closed without merging**
